import { beforeEach, afterEach, it, expect } from 'vitest'
import type { Browser } from 'webdriverio'
import { closeBrowser, BASE_URL, createBrowser, cdp } from './browser-helper'
import { seed, join, request, state, settled } from './fixtures'
let browser: Browser
beforeEach(async () => { browser = await createBrowser() })
afterEach(async () => { if (browser) await closeBrowser(browser) })
async function network(offline: boolean) {
    await cdp(browser, 'Network.enable')
    await cdp(browser, 'Network.emulateNetworkConditions', { offline, latency: 0, downloadThroughput: offline ? 0 : -1, uploadThroughput: offline ? 0 : -1 })
    await cdp(browser, 'Network.overrideNetworkState', { offline, latency: 0, downloadThroughput: offline ? 0 : -1, uploadThroughput: offline ? 0 : -1 })
}
async function rename(name: string) {
    await browser.$('[data-testid="edit-list-name"]').click()
    await browser.$('[data-testid="edit-list-input"]').setValue(name)
    await browser.keys('Enter')
    await browser.$('[data-testid="list-title"]').waitForDisplayed()
}
it('retains a genuine shared-field conflict and explicitly retries over the remote value', async () => {
    const id = await seed()
    await join(browser, id)
    await network(true)
    await rename('My offline name')
    expect((await request(`/list/${id}/name`, 'PUT', { name: 'Sam changed it', renamedBy: 'Sam' })).status).toBe(200)
    await network(false)
    await browser.$('summary=Review pending changes').waitForDisplayed({ timeout: 15000 })
    await browser.$('summary=Review pending changes').click()
    const text = await browser.$('body').getText()
    expect(text).toContain('My offline name')
    expect(text).toContain('Sam changed it')
    expect(text).toContain('Rejected (HTTP 409)')
    expect((await state(id)).name).toBe('Sam changed it')
    await browser.$('button=Apply saved edits over shared values').click()
    await settled(browser)
    expect((await state(id)).name).toBe('My offline name')
})
it('cancels and confirms discarding a conflict without overwriting shared values', async () => {
    const id = await seed()
    await join(browser, id)
    await network(true)
    await rename('Discard me')
    expect((await request(`/list/${id}/name`, 'PUT', { name: 'Keep shared', renamedBy: 'Sam' })).status).toBe(200)
    await network(false)
    await browser.$('summary=Review pending changes').waitForDisplayed({ timeout: 15000 })
    await browser.$('summary=Review pending changes').click()
    await browser.$('button=Discard edit and dependent item edits').click()
    await browser.dismissAlert()
    expect(await browser.$('button=Discard edit and dependent item edits').isDisplayed()).toBe(true)
    await browser.$('button=Discard edit and dependent item edits').click()
    await browser.acceptAlert()
    await settled(browser)
    expect((await state(id)).name).toBe('Keep shared')
    await browser.refresh()
    await browser.$('[data-testid="list-title"]').waitForDisplayed()
    expect(await browser.$('[data-testid="list-title"]').getText()).toBe('Keep shared')
})
it('shows a real transport failure during creation, retains the wizard and succeeds on retry', async () => {
    await browser.url(`${BASE_URL}/list/new`)
    await browser.$('#creator-name-input').waitForDisplayed()
    await browser.$('#creator-name-input').setValue('Retry creation')
    await browser.$('button=Continue').click()
    await browser.$('input[placeholder="Enter your name"]').waitForDisplayed()
    await browser.$('input[placeholder="Enter your name"]').setValue('Alex')
    await browser.$('button=Continue').click()
    await browser.$('#create-list-button').waitForClickable()
    await cdp(browser, 'Network.enable')
    await cdp(browser, 'Network.setBlockedURLs', { urls: ['*/api/v1/list/create'] })
    await browser.$('#create-list-button').click()
    await browser.$('[role="alert"]').waitForDisplayed()
    expect(await browser.$('[role="alert"]').getText()).toContain('Could not create the list')
    await cdp(browser, 'Network.setBlockedURLs', { urls: [] })
    await browser.$('#create-list-button').click()
    await browser.$('[data-testid="list-title"]').waitForDisplayed()
    expect(await browser.$('[data-testid="list-title"]').getText()).toBe('Retry creation')
})
it('rejects unsafe edits when durable local storage is unavailable', async () => {
    const id = await seed()
    await join(browser, id)
    await browser.execute(() => { Storage.prototype.setItem = () => { throw new DOMException('Quota exceeded', 'QuotaExceededError') } })
    await browser.$('input[placeholder="What needs to be done?"]').setValue('Must not disappear')
    await browser.$('button=Add').click()
    await browser.$('[role="alert"]').waitForDisplayed()
    expect(await browser.$('[role="alert"]').getText()).toContain('Edits cannot be saved safely')
    expect(Object.keys((await state(id)).items)).toHaveLength(0)
    expect(await browser.$('input[placeholder="What needs to be done?"]').getValue()).toBe('Must not disappear')
})
it('opens saved lists and refuses new-list creation while the production shell is offline', async () => {
    const id = await seed('Available offline')
    await join(browser, id)
    await browser.waitUntil(async () => browser.execute(() => !!navigator.serviceWorker.controller), { timeout: 15000 })
    await network(true)
    await browser.url(BASE_URL)
    await browser.$(`a[href="/list/${id}"]`).waitForClickable()
    await browser.$(`a[href="/list/${id}"]`).click()
    await browser.$('[data-testid="list-title"]').waitForDisplayed()
    expect(await browser.$('[data-testid="list-title"]').getText()).toBe('Available offline')
    await browser.url(`${BASE_URL}/list/new`)
    await browser.$('#creator-name-input').waitForDisplayed()
    await browser.$('#creator-name-input').setValue('Offline new')
    await browser.$('button=Continue').click()
    await browser.$('input[placeholder="Enter your name"]').waitForDisplayed()
    await browser.$('input[placeholder="Enter your name"]').setValue('Alex')
    await browser.$('button=Continue').click()
    await browser.$('#create-list-button').waitForClickable()
    // Chrome resets navigator's network override on a new service-worker navigation.
    await network(true)
    expect(await browser.execute(() => navigator.onLine)).toBe(false)
    await browser.$('#create-list-button').click()
    await browser.$('[role="alert"]').waitForDisplayed()
    expect(await browser.execute(() => navigator.onLine)).toBe(false)
    expect(await browser.$('[role="alert"]').getText()).toBe('Connect to the internet to create a new list.')
})
