import { beforeEach, afterEach, expect, it } from 'vitest'
import type { Browser } from 'webdriverio'
import { createBrowser, closeBrowser, BASE_URL, cdp } from './browser-helper'
import { seed, join, add, state, settled } from './fixtures'
let browser: Browser
beforeEach(async () => { browser = await createBrowser(undefined, null) })
afterEach(async () => { if (browser) await closeBrowser(browser) })
const key = 'togetherlist:clarity-consent:v1'
async function noAnalytics() {
    expect(await browser.$('#root').getAttribute('data-clarity-mask')).toBe('True')
    expect(await browser.$('meta[name="referrer"]').getAttribute('content')).toBe('no-referrer')
    expect(await browser.execute(() => !document.querySelector('script[src*="clarity.ms"]') && !('clarity' in window))).toBe(true)
}
it('persists opt-in, decline and revocation and exposes the complete privacy statement from landing', async () => {
    await browser.url(BASE_URL)
    await browser.$('button=Allow analytics').waitForClickable()
    await noAnalytics()
    await browser.$('button=Decline / revoke analytics').click()
    expect(await browser.$('[role="dialog"]').isExisting()).toBe(false)
    await browser.refresh()
    await browser.$('footer').waitForDisplayed()
    expect(await browser.$('footer').getText()).toContain('Analytics: declined.')
    await noAnalytics()
    await browser.$('button=Allow analytics').click()
    expect(await browser.$('[role="dialog"]').isExisting()).toBe(false)
    await browser.refresh()
    await browser.$('footer').waitForDisplayed()
    expect(await browser.execute((k) => localStorage.getItem(k), key)).toBe('accepted')
    await noAnalytics() // Test builds cannot send session data to Microsoft.
    await browser.$('footer').$('a=Privacy').click()
    await browser.$('h1=Privacy').waitForDisplayed()
    expect(await browser.execute(() => document.referrer)).toBe('')
    const body = await browser.$('main').getText()
    for (const text of ['behavioral metrics', 'heatmaps', 'session replay', 'first-party and third-party cookies', 'product improvement']) expect(body).toContain(text)
    expect(await browser.$('a=Microsoft Privacy Statement').getAttribute('href')).toBe('https://privacy.microsoft.com/privacystatement')
    await browser.$('button=Decline / revoke analytics').click()
    expect(await browser.$('[role="dialog"]').isExisting()).toBe(false)
    await browser.refresh()
    await browser.$('footer').waitForDisplayed()
    expect(await browser.execute((k) => localStorage.getItem(k), key)).toBe('declined')
})
it('keeps private shared lists functional with consent and privacy reachable, across reload and offline', async () => {
    const id = await seed('Private list name')
    await browser.url(BASE_URL)
    await browser.$('button=Allow analytics').waitForClickable()
    await browser.$('button=Allow analytics').click()
    expect(await browser.$('[role="dialog"]').isExisting()).toBe(false)
    await join(browser, id)
    await add(browser, 'Private item content')
    await settled(browser)
    expect(Object.values((await state(id)).items)).toEqual([expect.objectContaining({ title: 'Private item content', created_by: 'Alex' })])
    await noAnalytics()
    await browser.$('footer').$('a=Privacy').click()
    await browser.$('h1=Privacy').waitForDisplayed()
    await noAnalytics()
    await browser.url(`${BASE_URL}/list/${id}`)
    await browser.$('[data-testid="list-title"]').waitForDisplayed()
    await settled(browser)
    await browser.waitUntil(async () => browser.execute(() => !!navigator.serviceWorker.controller))
    await cdp(browser, 'Network.emulateNetworkConditions', { offline: true, latency: 0, downloadThroughput: 0, uploadThroughput: 0 })
    await browser.$('footer').$('a=Privacy').click()
    await browser.$('h1=Privacy').waitForDisplayed()
    await browser.$('button=Decline / revoke analytics').click()
    expect(await browser.$('[role="dialog"]').isExisting()).toBe(false)
    await browser.refresh()
    await browser.$('h1=Privacy').waitForDisplayed()
    expect(await browser.execute((k) => localStorage.getItem(k), key)).toBe('declined')
    await noAnalytics()
})
it('fails closed on storage errors and synchronizes choices between tabs without changing list state', async () => {
    const id = await seed('Unchanged private list')
    await join(browser, id)
    await browser.execute(() => { Storage.prototype.setItem = () => { throw new Error('quota') } })
    await browser.$('button=Allow analytics').click()
    expect(await browser.$('[role="dialog"]').isExisting()).toBe(true)
    await browser.$('[role="alert"]').waitForDisplayed()
    await noAnalytics()
    expect((await state(id)).name).toBe('Unchanged private list')
    await browser.refresh()
    await browser.$('button=Allow analytics').waitForClickable()
    await browser.$('button=Allow analytics').click()
    expect(await browser.$('[role="dialog"]').isExisting()).toBe(false)
    const original = await browser.getWindowHandle()
    await browser.newWindow(`${BASE_URL}/privacy`)
    await browser.$('button=Decline / revoke analytics').waitForClickable()
    await browser.$('button=Decline / revoke analytics').click()
    await browser.switchToWindow(original)
    await browser.waitUntil(async () => (await browser.$('footer').getText()).includes('Analytics: declined.'))
    await noAnalytics()
})
it('shows fixed consent and persists keyboard close as decline with footer re-enable', async () => {
    await browser.url(BASE_URL)
    const banner = browser.$('[role="dialog"]')
    await banner.waitForDisplayed()
    expect(await banner.getCSSProperty('position')).toMatchObject({ value: 'fixed' })
    await browser.execute(() => window.scrollTo(0, document.body.scrollHeight))
    expect(await browser.execute(() => { const r = document.querySelector('[role="dialog"]')!.getBoundingClientRect(); return r.top >= 0 && r.bottom <= innerHeight })).toBe(true)
    await browser.saveScreenshot('e2e-artifacts/consent-banner-desktop.png')
    await browser.execute(() => (document.querySelector('[role="dialog"] button[aria-label]') as HTMLElement).focus())
    await browser.keys('Enter')
    expect(await banner.isExisting()).toBe(false)
    expect(await browser.execute((k) => localStorage.getItem(k), key)).toBe('declined')
    await browser.refresh()
    await browser.$('footer').waitForDisplayed()
    expect(await banner.isExisting()).toBe(false)
    await browser.$('footer').$('button=Allow analytics').click()
    expect(await banner.isExisting()).toBe(false)
    await browser.$('footer').$('button=Decline / revoke analytics').click()
    expect(await browser.execute((k) => localStorage.getItem(k), key)).toBe('declined')
})
it('retains fixed consent after failed allow, decline and close writes', async () => {
    await browser.url(BASE_URL)
    await browser.$('[role="dialog"]').waitForDisplayed()
    await browser.execute(() => { Storage.prototype.setItem = () => { throw new Error('quota') } })
    for (const selector of ['button=Allow analytics', 'button=Decline / revoke analytics', 'button[aria-label]']) {
        await browser.$('[role="dialog"]').$(selector).click()
        await browser.$('[role="dialog"] [role="alert"]').waitForDisplayed()
        expect(await browser.execute((k) => localStorage.getItem(k), key)).toBeNull()
        await noAnalytics()
    }
})
it('fits mobile RTL consent controls in the viewport after translation', async () => {
    await cdp(browser, 'Emulation.setDeviceMetricsOverride', { width: 320, height: 640, deviceScaleFactor: 1, mobile: true })
    await browser.url(BASE_URL)
    await browser.execute(() => localStorage.setItem('i18nextLng', 'ar'))
    await browser.refresh()
    await browser.$('[role="dialog"]').waitForDisplayed()
    await browser.waitUntil(async () => (await browser.$('html').getAttribute('dir')) === 'rtl')
    expect(await browser.execute(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(await browser.execute(() => [...document.querySelectorAll('[role="dialog"] button')].every(el => {
        const r = el.getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth && r.top >= 0 && r.bottom <= innerHeight
    }))).toBe(true)
    await browser.saveScreenshot('e2e-artifacts/consent-banner-mobile-rtl.png')
    await browser.$('[role="dialog"] button[aria-label]').click()
    expect(await browser.execute((k) => localStorage.getItem(k), key)).toBe('declined')
    await browser.refresh()
    await browser.$('footer').waitForDisplayed()
    expect(await browser.$('[role="dialog"]').isExisting()).toBe(false)
})
