import { beforeEach, afterEach, it, expect } from 'vitest'
import type { Browser } from 'webdriverio'
import { closeBrowser, createBrowser, BASE_URL, cdp, setText } from './browser-helper'
import { seed, join, add, state, settled } from './fixtures'
let browser: Browser
beforeEach(async () => { browser = await createBrowser() })
afterEach(async () => { if (browser) await closeBrowser(browser) })

it('validates wizard fields, duplicate participants, removal and back navigation before creating', async () => {
    await browser.url(BASE_URL)
    await browser.$('details summary').click()
    expect(await browser.$('body').getText()).toContain('TogetherList')
    await browser.$('button=Create New List').click()
    await browser.$('#creator-name-input').waitForDisplayed()
    expect(await browser.$('button=Continue').isEnabled()).toBe(false)
    await browser.$('#creator-name-input').setValue('   ')
    expect(await browser.$('button=Continue').isEnabled()).toBe(false)
    await setText(browser, '#creator-name-input', '  Weekend trip 🏕️  ')
    await browser.$('button=Continue').click()
    await browser.$('input[placeholder="Enter your name"]').waitForDisplayed()
    expect(await browser.$('button=Continue').isEnabled()).toBe(false)
    await browser.$('input[placeholder="Enter your name"]').setValue('Alex')
    await browser.$('button=Continue').click()
    await browser.$('#participant-name-input').waitForDisplayed()
    expect(await browser.$('#add-participant-button').isEnabled()).toBe(false)
    await browser.$('#participant-name-input').setValue('Alex')
    await browser.$('#add-participant-button').click()
    expect(await browser.$('body').getText()).toContain('This name has already been added')
    await browser.$('#participant-name-input').setValue('Sam')
    await browser.$('#add-participant-button').click()
    await browser.$('#participant-name-input').setValue('Sam')
    await browser.$('#add-participant-button').click()
    expect(await browser.$('body').getText()).toContain('This name has already been added')
    await browser.$('button[aria-label="Remove Sam"]').click()
    expect(await browser.$('button[aria-label="Remove Sam"]').isExisting()).toBe(false)
    await browser.$('#back-button').click()
    await browser.$('input[placeholder="Enter your name"]').waitForDisplayed()
    await browser.$('input[placeholder="Enter your name"]').setValue('Alex')
    await browser.$('button=Continue').click()
    await browser.$('#participant-name-input').waitForDisplayed()
    await browser.$('#participant-name-input').setValue('Sam')
    await browser.keys('Enter')
    await browser.$('#create-list-button').click()
    await browser.$('[data-testid="list-title"]').waitForDisplayed()
    expect(await browser.$('[data-testid="list-title"]').getText()).toBe('Weekend trip 🏕️')
    const id = (await browser.getUrl()).split('/').pop()!
    expect(await state(id)).toMatchObject({ name: 'Weekend trip 🏕️', participants: ['Alex', 'Sam'] })
    expect(await browser.execute((id: string) => localStorage.getItem(`list:${id}:username`), id)).toBe('Alex')
    expect(await browser.$('body').getText()).toContain('No items yet')
})

it('persists and switches per-list identity and reopens saved lists from home', async () => {
    const first = await seed('First list'), second = await seed('Second list')
    await join(browser, first, 'Sam')
    await browser.refresh()
    await browser.$('[data-testid="list-title"]').waitForDisplayed()
    expect(await browser.$('[role="button"]').getText()).toContain('Sam')
    await browser.$('[role="button"]').click()
    await browser.$('button=Alex').waitForClickable()
    await browser.$('button=Alex').click()
    await join(browser, second, 'Sam')
    await browser.url(`${BASE_URL}/list/${first}`)
    await browser.$('[data-testid="list-title"]').waitForDisplayed()
    expect(await browser.$('[role="button"]').getText()).toContain('Alex')
    await browser.url(BASE_URL)
    await browser.$(`a[href="/list/${first}"]`).waitForClickable()
    expect(await browser.$(`a[href="/list/${second}"]`).isDisplayed()).toBe(true)
    await browser.$(`a[href="/list/${first}"]`).click()
    await browser.$('[data-testid="list-title"]').waitForDisplayed()
    expect(await browser.$('[data-testid="list-title"]').getText()).toBe('First list')
})

it('copies the real shared URL and synchronizes independent participant sessions both ways', async () => {
    const id = await seed()
    await join(browser, id)
    await cdp(browser, 'Browser.grantPermissions', { origin: BASE_URL, permissions: ['clipboardReadWrite', 'clipboardSanitizedWrite'] })
    await browser.$('button[aria-label="Share"]').click()
    await browser.$('span=Copied!').waitForDisplayed()
    const shared = await browser.execute(() => navigator.clipboard.readText())
    expect(shared).toBe(`${BASE_URL}/list/${id}`)
    const peer = await createBrowser()
    try {
        await peer.url(shared)
        await peer.$('button=Sam').waitForClickable()
        await peer.$('button=Sam').click()
        await add(browser, 'Bread')
        await peer.$('span=Bread').waitForDisplayed({ timeout: 12000 })
        await add(peer, 'Coffee')
        await browser.$('span=Coffee').waitForDisplayed({ timeout: 12000 })
        await peer.$('button[aria-label="Mark complete"]').click()
        await browser.$('button[aria-label="Mark incomplete"]').waitForDisplayed({ timeout: 12000 })
        await settled(peer)
        const items = Object.values((await state(id)).items)
        expect(items.map(item => item.created_by).sort()).toEqual(['Alex', 'Sam'])
        expect(items.find(item => item.completed)?.completed_by).toBe('Sam')
    } finally { await closeBrowser(peer) }
})

it('edits titles, cancels and rejects blanks, assigns multiple people and clears assignments', async () => {
    const id = await seed()
    await join(browser, id)
    expect(await browser.$('button=Add').isEnabled()).toBe(false)
    await browser.$('input[placeholder="What needs to be done?"]').setValue('   ')
    expect(await browser.$('button=Add').isEnabled()).toBe(false)
    await add(browser, 'Milk')
    await settled(browser)
    const edit = 'input[type="text"]:not([placeholder])'
    await browser.$('button[aria-label="Edit"]').click()
    await browser.$(edit).waitForDisplayed()
    await setText(browser, edit, 'Discarded')
    await browser.keys('Escape')
    expect(await browser.$('span=Milk').isDisplayed()).toBe(true)
    await browser.$('button[aria-label="Edit"]').click()
    await browser.$(edit).waitForDisplayed()
    await setText(browser, edit, '   ')
    await browser.keys('Enter')
    expect(await browser.$('span=Milk').isDisplayed()).toBe(true)
    await browser.$('button[aria-label="Edit"]').click()
    await browser.$(edit).waitForDisplayed()
    await setText(browser, edit, '  Oat milk 🥛  ')
    await browser.keys('Enter')
    await browser.$('span=Oat milk 🥛').waitForDisplayed()
    await browser.$('button[aria-expanded]:not([aria-haspopup])').click()
    await browser.$('textarea').waitForDisplayed()
    await browser.waitUntil(async () => (await browser.$('body').getText()).includes('Created by'))
    expect(await browser.$('body').getText()).toContain('Created by')
    const boxes = await browser.$$('input[type="checkbox"]')
    await boxes[0]!.click()
    await boxes[1]!.waitForEnabled()
    await boxes[1]!.click()
    await settled(browser)
    expect(Object.values((await state(id)).items)[0]).toMatchObject({ title: 'Oat milk 🥛', assigned_to: ['Alex', 'Sam'] })
    await browser.$('button=Clear assignment').click()
    await settled(browser)
    // The API omits empty assigned_to arrays from its JSON projection.
    expect(Object.values((await state(id)).items)[0]!.assigned_to).toBeUndefined()
    expect(await boxes[0]!.isSelected()).toBe(false)
    expect(await boxes[1]!.isSelected()).toBe(false)
    await boxes[1]!.click()
    await settled(browser)
    await browser.refresh()
    await browser.$('span=Oat milk 🥛').waitForDisplayed()
    expect(await browser.$('body').getText()).toContain('Assigned to: Sam')
    await browser.$('button[aria-expanded]:not([aria-haspopup])').click()
    await browser.$('button[aria-label="Mark complete"]').click()
    await browser.$('button[aria-label="Mark incomplete"]').waitForDisplayed()
    expect(await browser.$('textarea').isEnabled()).toBe(false)
    expect(await browser.$('input[type="checkbox"]').isEnabled()).toBe(false)
    expect(await browser.$('button[aria-label="Edit"]').isExisting()).toBe(false)
    await browser.waitUntil(async () => (await browser.$('body').getText()).includes('Completed by'))
    expect(await browser.$('body').getText()).toContain('Completed by')
})

it('cancels list rename and prevents empty names without changing persistent state', async () => {
    const id = await seed()
    await join(browser, id)
    await browser.$('[data-testid="edit-list-name"]').click()
    await browser.$('[data-testid="edit-list-input"]').setValue('   ')
    expect(await browser.$('[data-testid="save-list-name"]').isEnabled()).toBe(false)
    await browser.keys('Enter')
    expect(await browser.$('body').getText()).toContain('List name is required')
    await browser.keys('Escape')
    expect(await browser.$('[data-testid="list-title"]').getText()).toBe('Shared groceries')
    expect((await state(id)).name).toBe('Shared groceries')
})

it.each(['not-a-uuid', '11111111-1111-4111-8111-111111111111'])('shows a load error for invalid or missing shared list %s', async id => {
    await browser.url(`${BASE_URL}/list/${id}`)
    await browser.$('div=Failed to load list').waitForDisplayed()
    expect(await browser.$('input[placeholder="What needs to be done?"]').isExisting()).toBe(false)
})

it('keeps core actions usable at a mobile viewport', async () => {
    await browser.setWindowSize(390, 844)
    const id = await seed()
    await join(browser, id)
    await add(browser, 'Mobile task')
    await browser.$('button[aria-label="Mark complete"]').click()
    await browser.$('button[aria-label="Mark incomplete"]').waitForDisplayed()
    expect(await browser.execute(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
